"""Changed image as nullable

Revision ID: a2d2d3ed0c5d
Revises: e19c1cf4d1be
Create Date: 2024-07-24 03:56:59.684827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d2d3ed0c5d'
down_revision: Union[str, None] = 'e19c1cf4d1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'image',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint('pokemon_image_key', 'pokemon', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pokemon_image_key', 'pokemon', ['image'])
    op.alter_column('pokemon', 'image',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
