"""Changed type field to list type

Revision ID: e19c1cf4d1be
Revises: f5b89aee766f
Create Date: 2024-07-24 02:57:00.060007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19c1cf4d1be'
down_revision: Union[str, None] = 'f5b89aee766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('types', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('pokemon', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('pokemon', 'types')
    # ### end Alembic commands ###
